### ISSUE TITLE
remove support@evident.io from the README page

### ISSUE THREAD

**Issue by timberbee** [PaloAltoNetworks/evident-custom-signatures#58]
Since support@evident.io is not longer valid we should reference how they open a ticket with Palo Alto Networks
https://live.paloaltonetworks.com/t5/Support-Articles/Opening-a-Case-with-Customer-Support/ta-p/65755 are the instructions for opening a case now,

**Comment by timberbee** [comment]
Also need to change docs page link to 
https://www.paloaltonetworks.com/documentation/evident/evident-web-reference

**Comment by asetiawan** [comment]
@timberbee 

Sorry fo the delay. Links have been updated: https://github.com/PaloAltoNetworks/evident-custom-signatures
